/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class amplab_charles_JniTricks */

#ifndef _Included_amplab_charles_JniTricks
#define _Included_amplab_charles_JniTricks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     amplab_charles_JniTricks
 * Method:    allocateUninitializedLongArray
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_amplab_charles_JniTricks_allocateUninitializedLongArray
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
